version: "3"
services:
  app:
    container_name: traveloggia-node-api
    restart: always
    build: ./
    ports:
      - "9000:4000"
    volumes:
      - .:/app
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"